variables:
  APP_NAME: "th2-connectivity"
  MAJOR_VERSION: "1"
  MINOR_VERSION: "3"
  MAINTENANCE_VERSION: "0"

include:
  - project: 'vivarium/th2/pipelines'
    ref: master
    file: '/.gitlab-ci-java.yml'
